language: c
os: linux
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - check
            - libsubunit-dev
            - gcc-4.9
      env: COMPILER=gcc-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - check
            - libsubunit-dev
            - clang-3.7
      env: COMPILER=clang-3.7

addons:
  apt:
    packages:
      - check
      - libsubunit-dev

script: ./test.sh

