language: c
os: linux
sudo: false

compiler:
 - clang
 - gcc

addons:
  apt:
    sources:
     - llvm-toolchain-precise-3.8
    packages:
     - check
     - libsubunit-dev
     - clang-3.8

script: ./test.sh

